import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:livekit_translate/swayco/speech/ja_phonemizer.dart';

/// Proves the Dart Japanese phonemizer matches the validated Python reference
/// (MeloTTS `japanese.py` + the `MeloTTS-ONNX` ja token/tone contract) bit-for-bit.
/// Goldens generated by `scratchpad/ja_tts_phase0/gen_goldens.py`.
void main() {
  final tokens =
      parseTokens(File('test/data/ja_tokens.txt').readAsStringSync());
  final goldens = (jsonDecode(
    File('test/data/ja_phonemizer_goldens.json').readAsStringSync(),
  ) as List)
      .cast<Map<String, dynamic>>();

  test('tokens.txt parses to the expected size', () {
    expect(tokens.length, 219);
    expect(tokens['_'], 0);
    expect(tokens['?'], 209);
    expect(tokens[':'], 6);
  });

  group('phonemizeKatakana matches Python goldens', () {
    for (final g in goldens) {
      final kata = g['kata'] as String;
      test(kata, () {
        final expectedPhones = (g['phones'] as List).cast<String>();
        final expectedTokenIds = (g['token_ids'] as List).cast<int>();
        final expectedToneIds = (g['tone_ids'] as List).cast<int>();

        final phones = <String>['_', ...kataToPhonemes(kata), '_'];
        expect(phones, expectedPhones, reason: 'phones for $kata');

        final out = phonemizeKatakana(kata, tokens);
        expect(out.tokenIds, expectedTokenIds, reason: 'token ids for $kata');
        expect(out.toneIds, expectedToneIds, reason: 'tone ids for $kata');

        // Structural invariants from the contract.
        expect(out.tokenIds.length, out.toneIds.length);
        expect(out.tokenIds.length, phones.length * 2 + 1);
        expect(out.tokenIds.first, 0); // blank-interleaved
        expect(out.tokenIds.last, 0);
        // JP tone id is always tone_start (6) on real phones, 0 on blanks.
        for (var i = 0; i < out.toneIds.length; i++) {
          expect(out.toneIds[i], i.isEven ? 0 : 6, reason: 'tone[$i] of $kata');
        }
      });
    }
  });

  group('expandChoonpu rewrites long vowels to explicit kana', () {
    test('per-row vowel selection', () {
      expect(expandChoonpu('カー'), 'カア'); // a-row
      expect(expandChoonpu('キー'), 'キイ'); // i-row
      expect(expandChoonpu('スー'), 'スウ'); // u-row
      expect(expandChoonpu('ケー'), 'ケエ'); // e-row
      expect(expandChoonpu('コー'), 'コウ'); // o-row → オウ
      expect(expandChoonpu('リョーリ'), 'リョウリ'); // ryōri, matches kakasi
    });

    test('run of chōonpu keeps extending the same vowel', () {
      expect(expandChoonpu('カーー'), 'カアア');
    });

    test('leading or vowel-less chōonpu is dropped', () {
      expect(expandChoonpu('ーカ'), 'カ');
      expect(expandChoonpu('ンー'), 'ン'); // ン has no vowel
    });

    test('expanded reading no longer drops the long vowel', () {
      // Raw リョー loses the long vowel (ー → nothing); expanded keeps it.
      expect(kataToPhonemes('リョー'), ['ry', 'o']);
      expect(kataToPhonemes(expandChoonpu('リョー')), ['ry', 'o', 'u']);
    });
  });
}
