import 'app_strings.dart';

/// Les pays qu'on peut toucher sur le globe sans qu'ils soient ouverts : cle =
/// `name` du GeoJSON, code ISO2 (pour le drapeau), nom anglais et francais (avec
/// son article). Les pays OUVERTS (`kGlobeCountries`) n'y figurent pas.
const Map<String, ({String iso, String en, String fr, String frArt})>
    kWorldCountries = {
  'Afghanistan': (iso: 'af', en: 'Afghanistan', fr: 'Afghanistan', frArt: "l'Afghanistan"),
  'Albania': (iso: 'al', en: 'Albania', fr: 'Albanie', frArt: "l'Albanie"),
  'Algeria': (iso: 'dz', en: 'Algeria', fr: 'Algérie', frArt: "l'Algérie"),
  'Angola': (iso: 'ao', en: 'Angola', fr: 'Angola', frArt: "l'Angola"),
  'Armenia': (iso: 'am', en: 'Armenia', fr: 'Arménie', frArt: "l'Arménie"),
  'Australia': (iso: 'au', en: 'Australia', fr: 'Australie', frArt: "l'Australie"),
  'Austria': (iso: 'at', en: 'Austria', fr: 'Autriche', frArt: "l'Autriche"),
  'Azerbaijan': (iso: 'az', en: 'Azerbaijan', fr: 'Azerbaïdjan', frArt: "l'Azerbaïdjan"),
  'Bahamas': (iso: 'bs', en: 'Bahamas', fr: 'Bahamas', frArt: 'les Bahamas'),
  'Bangladesh': (iso: 'bd', en: 'Bangladesh', fr: 'Bangladesh', frArt: 'le Bangladesh'),
  'Belarus': (iso: 'by', en: 'Belarus', fr: 'Biélorussie', frArt: 'la Biélorussie'),
  'Belize': (iso: 'bz', en: 'Belize', fr: 'Belize', frArt: 'le Belize'),
  'Benin': (iso: 'bj', en: 'Benin', fr: 'Bénin', frArt: 'le Bénin'),
  'Bhutan': (iso: 'bt', en: 'Bhutan', fr: 'Bhoutan', frArt: 'le Bhoutan'),
  'Bolivia': (iso: 'bo', en: 'Bolivia', fr: 'Bolivie', frArt: 'la Bolivie'),
  'Bosnia and Herz.': (iso: 'ba', en: 'Bosnia and Herzegovina', fr: 'Bosnie-Herzégovine', frArt: 'la Bosnie-Herzégovine'),
  'Botswana': (iso: 'bw', en: 'Botswana', fr: 'Botswana', frArt: 'le Botswana'),
  'Brunei': (iso: 'bn', en: 'Brunei', fr: 'Brunei', frArt: 'le Brunei'),
  'Bulgaria': (iso: 'bg', en: 'Bulgaria', fr: 'Bulgarie', frArt: 'la Bulgarie'),
  'Burkina Faso': (iso: 'bf', en: 'Burkina Faso', fr: 'Burkina Faso', frArt: 'le Burkina Faso'),
  'Burundi': (iso: 'bi', en: 'Burundi', fr: 'Burundi', frArt: 'le Burundi'),
  'Cambodia': (iso: 'kh', en: 'Cambodia', fr: 'Cambodge', frArt: 'le Cambodge'),
  'Cameroon': (iso: 'cm', en: 'Cameroon', fr: 'Cameroun', frArt: 'le Cameroun'),
  'Central African Rep.': (iso: 'cf', en: 'Central African Republic', fr: 'République centrafricaine', frArt: 'la République centrafricaine'),
  'Chad': (iso: 'td', en: 'Chad', fr: 'Tchad', frArt: 'le Tchad'),
  'Chile': (iso: 'cl', en: 'Chile', fr: 'Chili', frArt: 'le Chili'),
  'China': (iso: 'cn', en: 'China', fr: 'Chine', frArt: 'la Chine'),
  'Congo': (iso: 'cg', en: 'Congo', fr: 'Congo', frArt: 'le Congo'),
  'Costa Rica': (iso: 'cr', en: 'Costa Rica', fr: 'Costa Rica', frArt: 'le Costa Rica'),
  "Côte d'Ivoire": (iso: 'ci', en: "Côte d'Ivoire", fr: "Côte d'Ivoire", frArt: "la Côte d'Ivoire"),
  'Croatia': (iso: 'hr', en: 'Croatia', fr: 'Croatie', frArt: 'la Croatie'),
  'Cuba': (iso: 'cu', en: 'Cuba', fr: 'Cuba', frArt: 'Cuba'),
  'Cyprus': (iso: 'cy', en: 'Cyprus', fr: 'Chypre', frArt: 'Chypre'),
  'Czechia': (iso: 'cz', en: 'Czechia', fr: 'Tchéquie', frArt: 'la Tchéquie'),
  'Dem. Rep. Congo': (iso: 'cd', en: 'DR Congo', fr: 'RD Congo', frArt: 'la RD Congo'),
  'Denmark': (iso: 'dk', en: 'Denmark', fr: 'Danemark', frArt: 'le Danemark'),
  'Djibouti': (iso: 'dj', en: 'Djibouti', fr: 'Djibouti', frArt: 'Djibouti'),
  'Dominican Rep.': (iso: 'do', en: 'Dominican Republic', fr: 'République dominicaine', frArt: 'la République dominicaine'),
  'Ecuador': (iso: 'ec', en: 'Ecuador', fr: 'Équateur', frArt: "l'Équateur"),
  'Egypt': (iso: 'eg', en: 'Egypt', fr: 'Égypte', frArt: "l'Égypte"),
  'El Salvador': (iso: 'sv', en: 'El Salvador', fr: 'Salvador', frArt: 'le Salvador'),
  'Eq. Guinea': (iso: 'gq', en: 'Equatorial Guinea', fr: 'Guinée équatoriale', frArt: 'la Guinée équatoriale'),
  'Eritrea': (iso: 'er', en: 'Eritrea', fr: 'Érythrée', frArt: "l'Érythrée"),
  'Estonia': (iso: 'ee', en: 'Estonia', fr: 'Estonie', frArt: "l'Estonie"),
  'eSwatini': (iso: 'sz', en: 'Eswatini', fr: 'Eswatini', frArt: "l'Eswatini"),
  'Ethiopia': (iso: 'et', en: 'Ethiopia', fr: 'Éthiopie', frArt: "l'Éthiopie"),
  'Falkland Is.': (iso: 'fk', en: 'Falkland Islands', fr: 'Îles Malouines', frArt: 'les îles Malouines'),
  'Fiji': (iso: 'fj', en: 'Fiji', fr: 'Fidji', frArt: 'les Fidji'),
  'Finland': (iso: 'fi', en: 'Finland', fr: 'Finlande', frArt: 'la Finlande'),
  'Gabon': (iso: 'ga', en: 'Gabon', fr: 'Gabon', frArt: 'le Gabon'),
  'Gambia': (iso: 'gm', en: 'Gambia', fr: 'Gambie', frArt: 'la Gambie'),
  'Georgia': (iso: 'ge', en: 'Georgia', fr: 'Géorgie', frArt: 'la Géorgie'),
  'Ghana': (iso: 'gh', en: 'Ghana', fr: 'Ghana', frArt: 'le Ghana'),
  'Greece': (iso: 'gr', en: 'Greece', fr: 'Grèce', frArt: 'la Grèce'),
  'Greenland': (iso: 'gl', en: 'Greenland', fr: 'Groenland', frArt: 'le Groenland'),
  'Guatemala': (iso: 'gt', en: 'Guatemala', fr: 'Guatemala', frArt: 'le Guatemala'),
  'Guinea': (iso: 'gn', en: 'Guinea', fr: 'Guinée', frArt: 'la Guinée'),
  'Guinea-Bissau': (iso: 'gw', en: 'Guinea-Bissau', fr: 'Guinée-Bissau', frArt: 'la Guinée-Bissau'),
  'Guyana': (iso: 'gy', en: 'Guyana', fr: 'Guyana', frArt: 'le Guyana'),
  'Haiti': (iso: 'ht', en: 'Haiti', fr: 'Haïti', frArt: 'Haïti'),
  'Honduras': (iso: 'hn', en: 'Honduras', fr: 'Honduras', frArt: 'le Honduras'),
  'Hungary': (iso: 'hu', en: 'Hungary', fr: 'Hongrie', frArt: 'la Hongrie'),
  'Iceland': (iso: 'is', en: 'Iceland', fr: 'Islande', frArt: "l'Islande"),
  'India': (iso: 'in', en: 'India', fr: 'Inde', frArt: "l'Inde"),
  'Indonesia': (iso: 'id', en: 'Indonesia', fr: 'Indonésie', frArt: "l'Indonésie"),
  'Iran': (iso: 'ir', en: 'Iran', fr: 'Iran', frArt: "l'Iran"),
  'Iraq': (iso: 'iq', en: 'Iraq', fr: 'Irak', frArt: "l'Irak"),
  'Ireland': (iso: 'ie', en: 'Ireland', fr: 'Irlande', frArt: "l'Irlande"),
  'Israel': (iso: 'il', en: 'Israel', fr: 'Israël', frArt: 'Israël'),
  'Italy': (iso: 'it', en: 'Italy', fr: 'Italie', frArt: "l'Italie"),
  'Jamaica': (iso: 'jm', en: 'Jamaica', fr: 'Jamaïque', frArt: 'la Jamaïque'),
  'Jordan': (iso: 'jo', en: 'Jordan', fr: 'Jordanie', frArt: 'la Jordanie'),
  'Kazakhstan': (iso: 'kz', en: 'Kazakhstan', fr: 'Kazakhstan', frArt: 'le Kazakhstan'),
  'Kenya': (iso: 'ke', en: 'Kenya', fr: 'Kenya', frArt: 'le Kenya'),
  'Kosovo': (iso: 'xk', en: 'Kosovo', fr: 'Kosovo', frArt: 'le Kosovo'),
  'Kuwait': (iso: 'kw', en: 'Kuwait', fr: 'Koweït', frArt: 'le Koweït'),
  'Kyrgyzstan': (iso: 'kg', en: 'Kyrgyzstan', fr: 'Kirghizistan', frArt: 'le Kirghizistan'),
  'Laos': (iso: 'la', en: 'Laos', fr: 'Laos', frArt: 'le Laos'),
  'Latvia': (iso: 'lv', en: 'Latvia', fr: 'Lettonie', frArt: 'la Lettonie'),
  'Lebanon': (iso: 'lb', en: 'Lebanon', fr: 'Liban', frArt: 'le Liban'),
  'Lesotho': (iso: 'ls', en: 'Lesotho', fr: 'Lesotho', frArt: 'le Lesotho'),
  'Liberia': (iso: 'lr', en: 'Liberia', fr: 'Liberia', frArt: 'le Liberia'),
  'Libya': (iso: 'ly', en: 'Libya', fr: 'Libye', frArt: 'la Libye'),
  'Lithuania': (iso: 'lt', en: 'Lithuania', fr: 'Lituanie', frArt: 'la Lituanie'),
  'Luxembourg': (iso: 'lu', en: 'Luxembourg', fr: 'Luxembourg', frArt: 'le Luxembourg'),
  'Macedonia': (iso: 'mk', en: 'North Macedonia', fr: 'Macédoine du Nord', frArt: 'la Macédoine du Nord'),
  'Madagascar': (iso: 'mg', en: 'Madagascar', fr: 'Madagascar', frArt: 'Madagascar'),
  'Malawi': (iso: 'mw', en: 'Malawi', fr: 'Malawi', frArt: 'le Malawi'),
  'Malaysia': (iso: 'my', en: 'Malaysia', fr: 'Malaisie', frArt: 'la Malaisie'),
  'Mali': (iso: 'ml', en: 'Mali', fr: 'Mali', frArt: 'le Mali'),
  'Mauritania': (iso: 'mr', en: 'Mauritania', fr: 'Mauritanie', frArt: 'la Mauritanie'),
  'Moldova': (iso: 'md', en: 'Moldova', fr: 'Moldavie', frArt: 'la Moldavie'),
  'Mongolia': (iso: 'mn', en: 'Mongolia', fr: 'Mongolie', frArt: 'la Mongolie'),
  'Montenegro': (iso: 'me', en: 'Montenegro', fr: 'Monténégro', frArt: 'le Monténégro'),
  'Mozambique': (iso: 'mz', en: 'Mozambique', fr: 'Mozambique', frArt: 'le Mozambique'),
  'Myanmar': (iso: 'mm', en: 'Myanmar', fr: 'Birmanie', frArt: 'la Birmanie'),
  'Namibia': (iso: 'na', en: 'Namibia', fr: 'Namibie', frArt: 'la Namibie'),
  'Nepal': (iso: 'np', en: 'Nepal', fr: 'Népal', frArt: 'le Népal'),
  'Netherlands': (iso: 'nl', en: 'Netherlands', fr: 'Pays-Bas', frArt: 'les Pays-Bas'),
  'New Caledonia': (iso: 'nc', en: 'New Caledonia', fr: 'Nouvelle-Calédonie', frArt: 'la Nouvelle-Calédonie'),
  'New Zealand': (iso: 'nz', en: 'New Zealand', fr: 'Nouvelle-Zélande', frArt: 'la Nouvelle-Zélande'),
  'Nicaragua': (iso: 'ni', en: 'Nicaragua', fr: 'Nicaragua', frArt: 'le Nicaragua'),
  'Niger': (iso: 'ne', en: 'Niger', fr: 'Niger', frArt: 'le Niger'),
  'Nigeria': (iso: 'ng', en: 'Nigeria', fr: 'Nigeria', frArt: 'le Nigeria'),
  'North Korea': (iso: 'kp', en: 'North Korea', fr: 'Corée du Nord', frArt: 'la Corée du Nord'),
  'Norway': (iso: 'no', en: 'Norway', fr: 'Norvège', frArt: 'la Norvège'),
  'Oman': (iso: 'om', en: 'Oman', fr: 'Oman', frArt: 'Oman'),
  'Pakistan': (iso: 'pk', en: 'Pakistan', fr: 'Pakistan', frArt: 'le Pakistan'),
  'Palestine': (iso: 'ps', en: 'Palestine', fr: 'Palestine', frArt: 'la Palestine'),
  'Panama': (iso: 'pa', en: 'Panama', fr: 'Panama', frArt: 'le Panama'),
  'Papua New Guinea': (iso: 'pg', en: 'Papua New Guinea', fr: 'Papouasie-Nouvelle-Guinée', frArt: 'la Papouasie-Nouvelle-Guinée'),
  'Paraguay': (iso: 'py', en: 'Paraguay', fr: 'Paraguay', frArt: 'le Paraguay'),
  'Peru': (iso: 'pe', en: 'Peru', fr: 'Pérou', frArt: 'le Pérou'),
  'Poland': (iso: 'pl', en: 'Poland', fr: 'Pologne', frArt: 'la Pologne'),
  'Portugal': (iso: 'pt', en: 'Portugal', fr: 'Portugal', frArt: 'le Portugal'),
  'Puerto Rico': (iso: 'pr', en: 'Puerto Rico', fr: 'Porto Rico', frArt: 'Porto Rico'),
  'Qatar': (iso: 'qa', en: 'Qatar', fr: 'Qatar', frArt: 'le Qatar'),
  'Romania': (iso: 'ro', en: 'Romania', fr: 'Roumanie', frArt: 'la Roumanie'),
  'Russia': (iso: 'ru', en: 'Russia', fr: 'Russie', frArt: 'la Russie'),
  'Rwanda': (iso: 'rw', en: 'Rwanda', fr: 'Rwanda', frArt: 'le Rwanda'),
  'S. Sudan': (iso: 'ss', en: 'South Sudan', fr: 'Soudan du Sud', frArt: 'le Soudan du Sud'),
  'Saudi Arabia': (iso: 'sa', en: 'Saudi Arabia', fr: 'Arabie saoudite', frArt: "l'Arabie saoudite"),
  'Senegal': (iso: 'sn', en: 'Senegal', fr: 'Sénégal', frArt: 'le Sénégal'),
  'Serbia': (iso: 'rs', en: 'Serbia', fr: 'Serbie', frArt: 'la Serbie'),
  'Sierra Leone': (iso: 'sl', en: 'Sierra Leone', fr: 'Sierra Leone', frArt: 'la Sierra Leone'),
  'Slovakia': (iso: 'sk', en: 'Slovakia', fr: 'Slovaquie', frArt: 'la Slovaquie'),
  'Slovenia': (iso: 'si', en: 'Slovenia', fr: 'Slovénie', frArt: 'la Slovénie'),
  'Solomon Is.': (iso: 'sb', en: 'Solomon Islands', fr: 'Îles Salomon', frArt: 'les îles Salomon'),
  'Somalia': (iso: 'so', en: 'Somalia', fr: 'Somalie', frArt: 'la Somalie'),
  'South Africa': (iso: 'za', en: 'South Africa', fr: 'Afrique du Sud', frArt: "l'Afrique du Sud"),
  'South Korea': (iso: 'kr', en: 'South Korea', fr: 'Corée du Sud', frArt: 'la Corée du Sud'),
  'Sri Lanka': (iso: 'lk', en: 'Sri Lanka', fr: 'Sri Lanka', frArt: 'le Sri Lanka'),
  'Sudan': (iso: 'sd', en: 'Sudan', fr: 'Soudan', frArt: 'le Soudan'),
  'Suriname': (iso: 'sr', en: 'Suriname', fr: 'Suriname', frArt: 'le Suriname'),
  'Switzerland': (iso: 'ch', en: 'Switzerland', fr: 'Suisse', frArt: 'la Suisse'),
  'Syria': (iso: 'sy', en: 'Syria', fr: 'Syrie', frArt: 'la Syrie'),
  'Taiwan': (iso: 'tw', en: 'Taiwan', fr: 'Taïwan', frArt: 'Taïwan'),
  'Tajikistan': (iso: 'tj', en: 'Tajikistan', fr: 'Tadjikistan', frArt: 'le Tadjikistan'),
  'Tanzania': (iso: 'tz', en: 'Tanzania', fr: 'Tanzanie', frArt: 'la Tanzanie'),
  'Thailand': (iso: 'th', en: 'Thailand', fr: 'Thaïlande', frArt: 'la Thaïlande'),
  'Timor-Leste': (iso: 'tl', en: 'Timor-Leste', fr: 'Timor oriental', frArt: 'le Timor oriental'),
  'Togo': (iso: 'tg', en: 'Togo', fr: 'Togo', frArt: 'le Togo'),
  'Trinidad and Tobago': (iso: 'tt', en: 'Trinidad and Tobago', fr: 'Trinité-et-Tobago', frArt: 'Trinité-et-Tobago'),
  'Tunisia': (iso: 'tn', en: 'Tunisia', fr: 'Tunisie', frArt: 'la Tunisie'),
  'Turkey': (iso: 'tr', en: 'Turkey', fr: 'Turquie', frArt: 'la Turquie'),
  'Turkmenistan': (iso: 'tm', en: 'Turkmenistan', fr: 'Turkménistan', frArt: 'le Turkménistan'),
  'Uganda': (iso: 'ug', en: 'Uganda', fr: 'Ouganda', frArt: "l'Ouganda"),
  'Ukraine': (iso: 'ua', en: 'Ukraine', fr: 'Ukraine', frArt: "l'Ukraine"),
  'United Arab Emirates': (iso: 'ae', en: 'United Arab Emirates', fr: 'Émirats arabes unis', frArt: 'les Émirats arabes unis'),
  'United Kingdom': (iso: 'gb', en: 'United Kingdom', fr: 'Royaume-Uni', frArt: 'le Royaume-Uni'),
  'United States of America': (iso: 'us', en: 'United States', fr: 'États-Unis', frArt: 'les États-Unis'),
  'Uruguay': (iso: 'uy', en: 'Uruguay', fr: 'Uruguay', frArt: "l'Uruguay"),
  'Uzbekistan': (iso: 'uz', en: 'Uzbekistan', fr: 'Ouzbékistan', frArt: "l'Ouzbékistan"),
  'Vanuatu': (iso: 'vu', en: 'Vanuatu', fr: 'Vanuatu', frArt: 'le Vanuatu'),
  'Venezuela': (iso: 've', en: 'Venezuela', fr: 'Venezuela', frArt: 'le Venezuela'),
  'Vietnam': (iso: 'vn', en: 'Vietnam', fr: 'Viêt Nam', frArt: 'le Viêt Nam'),
  'W. Sahara': (iso: 'eh', en: 'Western Sahara', fr: 'Sahara occidental', frArt: 'le Sahara occidental'),
  'Yemen': (iso: 'ye', en: 'Yemen', fr: 'Yémen', frArt: 'le Yémen'),
  'Zambia': (iso: 'zm', en: 'Zambia', fr: 'Zambie', frArt: 'la Zambie'),
  'Zimbabwe': (iso: 'zw', en: 'Zimbabwe', fr: 'Zimbabwe', frArt: 'le Zimbabwe'),
};

bool _missing(String t, String key) => t.isEmpty || t == key;

/// Nom d'un pays dans la langue de l'app : `country_xx` s'il existe, sinon le
/// francais / l'anglais de [kWorldCountries], sinon la cle.
String worldCountryName(String key) {
  final info = kWorldCountries[key];
  if (info == null) return key;
  final t = AppStrings.t('country_${info.iso}');
  if (!_missing(t, 'country_${info.iso}')) return t;
  return AppStrings.currentBcp47.value == 'fr' ? info.fr : info.en;
}

/// Le meme avec son article en francais (l'Inde), sinon le nom nu.
String worldCountryArticle(String key) {
  final info = kWorldCountries[key];
  if (info == null) return key;
  final t = AppStrings.t('country_art_${info.iso}');
  if (!_missing(t, 'country_art_${info.iso}')) return t;
  return AppStrings.currentBcp47.value == 'fr'
      ? info.frArt
      : worldCountryName(key);
}
